# Generated by Django 5.0 on 2024-03-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_productdetails_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='phone_no',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
