# Generated by Django 5.0 on 2024-03-30 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_e_mail_product_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='address',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
