# Generated by Django 5.0 on 2024-04-28 14:54

import django.db.models.deletion
import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_product_quantity_product_product_image1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favourite',
            name='product',
        ),
        migrations.RemoveField(
            model_name='favourite',
            name='user',
        ),
        migrations.CreateModel(
            name='shopname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=150)),
                ('shop_image', models.ImageField(blank=True, null=True, upload_to=shop.models.getFileName)),
                ('catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.catagory')),
            ],
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Favourite',
        ),
    ]
