# Generated by Django 5.0 on 2024-04-28 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_remove_favourite_product_remove_favourite_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='shopname',
        ),
    ]
