# Generated by Django 5.0 on 2024-04-29 15:49

import django.db.models.deletion
import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_product_shop_image_product_shop_name_delete_shopname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='shop_image',
        ),
        migrations.CreateModel(
            name='shopname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=150)),
                ('shop_image', models.ImageField(blank=True, null=True, upload_to=shop.models.getFileName)),
                ('catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.catagory')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='shop_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.shopname'),
        ),
    ]
